#ifndef DSCPLUGIN_COOMATRIX_GLOBAL_H
#define DSCPLUGIN_COOMATRIX_GLOBAL_H

#include <QtCore/qglobal.h>

//#define DSCPLUGIN_COOMATRIX_LIBRARY

#if defined( DSCPLUGIN_COOMATRIX_LIBRARY)
#  define DSCPLUGIN_COOMATRIX_LIBRARY Q_DECL_EXPORT
#else
#  define DSCPLUGIN_COOMATRIX_LIBRARY Q_DECL_IMPORT
#endif

#endif
